### ISSUE TITLE
Bug: Sleep log is not updating after deleting a sleep window

### ISSUE THREAD

**Issue by nathaliaesper** [childmindresearch/app-actigraphy#69]
### Description

If you delete a valid sleep window and do not add one again, the sleep log stops updating, and you can see the following error on the command line every time you change the day:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dash/dash.py", line 1310, in dispatch
    ctx.run(
  File "/usr/local/lib/python3.11/site-packages/dash/_callback.py", line 442, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/actigraphy/core/callback_manager.py", line 92, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/actigraphy/components/graph.py", line 380, in adjust_range_slider
    ggir_files.write_sleeplog(file_manager)
  File "/app/src/actigraphy/io/ggir_files.py", line 109, in write_sleeplog
    onset_times = [day.sleep_times[0].onset_with_tz for day in subject.days]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/actigraphy/io/ggir_files.py", line 109, in <listcomp>
    onset_times = [day.sleep_times[0].onset_with_tz for day in subject.days]
                   ~~~~~~~~~~~~~~~^^^
IndexError: list index out of range`

### Steps to Reproduce

To reproduce this issue:
1. Run the following command:
`docker run -p 127.0.0.1:8051:8051 --volume ~/Documents/TEMP/actigraphy_tests/subjects:/data --volume pwd/assets:/app/assets cmidair/actigraphy:latest`

2. Delete any sleep window.




### Expected Results

The expected result is to automatically include that night on the `data_cleaning` file, under the column `night_part4`. The app should continue automatically saving the sleep log.

### Actual Results

The sleep log file is not updating after you delete a valid sleep window on the app.

### Additional Notes

_No response_

**Comment by ReinderVosDeWael** [comment]
This requires further specification:

- What happens if, on a night without sleep windows, the user toggles exclude this night to off? Or should this button be automatically turned on and disabled?
    - @gkiar If we're adding links to control the enabled/disabled state of the toggle component based on the slider data (from a UI perspective the most sensible option) I will have to remind you that _this_ is an example of the type of issue why I suggested we switch away from Dash; this feature will be another cut in the thousand cuts that make tracing the flow of information and callbacks exceedingly difficult. 
- Is 1-Jan-1970 OK for the default value in the GGIR log if no value exists. 
- (Tangentially related) How should I determine which sleep window has to be included in the standard GGIR file. Current default is the first *in the database*.

**Comment by ReinderVosDeWael** [comment]
Discussed w/ Greg: The UI will remain unaltered but if the user sets the toggle to false, we'll still report it as true in the GGIR data, despite what the user tells us.
